import type { AvatarState } from "@manglara/shared";
import { TalkingHead } from "@met4citizen/talkinghead";
import type { PlaybackMetricsMessage } from "@met4citizen/talkinghead";
import { CanvasTexture, MeshBasicMaterial, SRGBColorSpace } from "three";
import type { Mesh } from "three";
// Statically bundle the English lip-sync processor. TalkingHead otherwise loads
// it via `import('./lipsync-en.mjs')` - an un-analyzable dynamic import that
// Rollup can't bundle, so in production it 404s at /assets/lipsync-en.mjs. We
// import it here (Vite bundles it) and register it on the instance below.
import { LipsyncEn } from "@met4citizen/talkinghead/modules/lipsync-en.mjs";
import { spanishTextToUnits, unitsDuration } from "./lipsync-es";
import { VisemeDriver } from "./viseme-driver";
import { blendLipShapes } from "./lip-shapes";
import type { LipShape } from "./lip-shapes";

/** Assistant audio from Gemini Live is 24 kHz, 16-bit LE PCM. */
const GEMINI_SAMPLE_RATE = 24000;

/**
 * Mouth-shape strength. Higher than TalkingHead's own 0.6 for visemes because
 * the whole point here is that the shapes be readable.
 */
const VISEME_LEVEL = 0.78;
/** Lip closure (P/B/M, F/V) has to look definite to read as a closure. */
const VISEME_LEVEL_CLOSED = 0.95;

/**
 * How long the shape queue must stay dry, with audio still playing, before the
 * audio-driven fallback takes the mouth back. Long enough that the ordinary gaps
 * between transcript fragments never trigger a swap.
 */
const HANDOVER_AFTER_DRY_MS = 900;

/**
 * How often the playback worklet reports its queue depth. Its queue is the only
 * exact measure of the true playback position (see `onPlaybackMetrics`), so this
 * is the lip-sync clock's sample rate. 25 Hz costs one small postMessage per
 * 40 ms and keeps the extrapolation window between reports below one frame.
 */
const PLAYBACK_METRICS_HZ = 25;
/**
 * Ceiling on how far the clock may be extrapolated past the last report. Reports
 * land every ~41 ms in practice, so three intervals is ample slack for jitter while
 * bounding how wrong the clock can be between two of them.
 */
const METRICS_EXTRAPOLATE_MAX_MS = 120;
/**
 * Ceiling on the speaker-latency compensation. Over-compensating would push the
 * mouth BEHIND the voice, which is worse than not compensating at all.
 */
const MAX_OUTPUT_LATENCY_MS = 300;
/** Where the learned speaking tempo is kept between sessions. */
const PACE_RATE_KEY = "manglara.lipsync.paceRate";

/**
 * Custom avatar generated by scripts/avatar-rig-transfer/.
 * Transfered rig + 52 ARKit + 15 Oculus + 5 extra blend shapes from
 * TalkingHead's brunette.glb reference onto the user's manglara.glb mesh.
 */
const AVATAR_URL = import.meta.env.VITE_AVATAR_URL ?? "/custom_avatar.glb";

/**
 * Facial mood expressiveness (rig-safe: moods drive only face + head-sway, never
 * the smeared body/arm skin weights, so they never balloon the dress). Manglara's
 * resting and speaking face is warm and smiling with animated brows and head-sway
 * ("happy" carries a dedicated speaking animation), dropping to a calmer "neutral"
 * face while she glances away thinking. "love" is deliberately NOT used: its
 * baseline half-lids the eyes (eyeBlink 0.6), which reads as dreamy, not
 * professional. See animMoods in @met4citizen/talkinghead.
 */
const DEFAULT_MOOD = "happy";
const THINKING_MOOD = "neutral";

/**
 * Rig-safe "body language" gestures. Manglara's arm geometry is welded to the
 * SHOULDER bone (the arm skeleton sits in an A-pose outside the arms-down mesh),
 * so any real arm gesture balloons her dress - measured live: `handup` inflates
 * the skirt into a ~30 cm "wing"; see the gesture-rig-validation memory. These
 * templates rotate ONLY the torso/neck/head bones (Spine1/Spine2/Neck/Head),
 * which deform cleanly, giving her lively presenting body language with ZERO
 * ballooning. Values are absolute local Euler rotations (rad), kept small for a
 * warm, professional read. Verified in-engine (full-body screenshots).
 */
type BoneEuler = { x: number; y: number; z: number };
const BODY_GESTURES: Record<string, Record<string, BoneEuler>> = {
  // Engaged lean toward the user - the workhorse "I'm presenting to you" beat.
  leanIn: {
    "Spine1.rotation": { x: 0.09, y: 0.0, z: 0.0 },
    "Spine2.rotation": { x: 0.05, y: 0.03, z: 0.0 },
    "Neck.rotation": { x: -0.05, y: 0.05, z: 0.0 },
    "Head.rotation": { x: -0.03, y: 0.07, z: 0.0 },
  },
  // Gentle affirmation nod.
  nod: {
    "Neck.rotation": { x: 0.1, y: 0.0, z: 0.0 },
    "Head.rotation": { x: 0.12, y: 0.0, z: 0.0 },
  },
  // Curious head tilt - warmth while making a point.
  tiltCurious: {
    "Neck.rotation": { x: 0.0, y: 0.03, z: 0.1 },
    "Head.rotation": { x: -0.02, y: 0.08, z: 0.09 },
  },
  // Subtle upper-body weight shift for liveliness between the stronger beats.
  sway: {
    "Spine1.rotation": { x: 0.02, y: 0.06, z: -0.05 },
    "Neck.rotation": { x: 0.0, y: -0.04, z: 0.03 },
    "Head.rotation": { x: 0.0, y: -0.03, z: 0.04 },
  },
};
/** Weighted toward the gentle lean/nod; one is played every few seconds while speaking. */
const BODY_GESTURE_POOL = ["leanIn", "nod", "leanIn", "tiltCurious", "nod", "sway"];

/** Vendored HeadAudio (audio-driven viseme detection). Served from public/. */
const HEADAUDIO_BASE = "/headaudio";

/**
 * The learned speaking tempo, kept between sessions. It is only exactly measurable
 * at the end of a turn, so without this the first turn of every call runs on the
 * duration table's guess and visibly drifts before the first correction lands.
 */
function loadPaceRate(): number | null {
  try {
    const raw = window.localStorage.getItem(PACE_RATE_KEY);
    if (!raw) return null;
    const rate = Number.parseFloat(raw);
    return Number.isFinite(rate) && rate > 0 ? rate : null;
  } catch {
    return null; // private mode / storage disabled
  }
}

function savePaceRate(rate: number): void {
  try {
    window.localStorage.setItem(PACE_RATE_KEY, String(rate));
  } catch {
    // ignore: losing the calibration only costs one turn next time
  }
}

export interface AvatarControllerCallbacks {
  /** Fires true when the avatar starts speaking audio, false when it stops. */
  onSpeakingChange?: (speaking: boolean) => void;
  onReady?: () => void;
  onError?: (error: unknown) => void;
}

/**
 * Bridges the app to the met4citizen avatar stack:
 *  - TalkingHead renders the RPM avatar, plays the streamed PCM and runs the
 *    built-in natural animations (blink, head move, eye contact, breathing).
 *  - HeadAudio taps the playback graph and produces Oculus visemes from the
 *    audio itself (language-agnostic), which drive the mouth morph targets.
 *
 * Lifecycle: construct once, `init()` on mount (loads avatar, idle), then
 * `startStream()`/`stopStream()` per call, feeding chunks with `feedAudio()`.
 */
export class AvatarController {
  private head: TalkingHead | null = null;
  // HeadAudio is an untyped, dynamically-imported AudioWorkletNode.
  private headAudio: {
    update(dt: number): void;
    onvalue: ((key: string, value: number) => void) | null;
    disconnect?: () => void;
  } | null = null;
  private headAudioReady = false;
  private streaming = false;
  private lastState: AvatarState | null = null;
  private _ready = false;
  private disposed = false;
  /** Self-rescheduling timer that plays rig-safe body-language while speaking. */
  private bodyLangTimer: ReturnType<typeof setTimeout> | null = null;
  /** Alternate the mirror flag so beats don't always lean the same way. */
  private bodyLangMirror = false;

  // Sprite mouth: the avatar GLB ships a "MouthOverlay" patch hugging the
  // mouth region (transparent at rest). Each frame we paint a viseme-driven
  // mouth (dark cavity + teeth) onto it, so the character visibly opens her
  // mouth while talking - morphs alone can't show a cavity on a sealed mesh.
  private mouthMesh: Mesh | null = null;
  private mouthCtx: CanvasRenderingContext2D | null = null;
  private mouthTex: CanvasTexture | null = null;
  private lastShape: LipShape | null = null;

  // Text-driven lip-sync. Mouth shapes come from the transcript and are consumed
  // against the audio playback clock rather than scheduled at absolute times:
  // Gemini streams audio far faster than real time, so "how much audio we were
  // handed" says nothing about what is being heard right now. See viseme-driver.
  private driver = new VisemeDriver();
  /** Duration of PCM handed to playback, ms. Exact - it's a byte count. */
  private audioFedMs = 0;

  // --- the playback clock ---------------------------------------------------
  // Measured, never integrated. TalkingHead clamps the frame delta it hands to
  // `opt.update` at two frame durations (talkinghead.mjs: `if (dt > 2 *
  // animFrameDur) dt = 2 * animFrameDur`, 66 ms at modelFPS 30), so a clock built
  // by adding up those deltas permanently loses every dropped frame. This app drops
  // frames on a schedule - the webcam capture JPEG-encodes and base64s a 640x480
  // frame on the main thread every 1.5 s for the whole call - so that clock ran
  // slower than the voice and the mouth fell further behind the longer she spoke.
  /** Audio actually heard as of the last worklet report, ms. */
  private syncPlayedMs = 0;
  /** `performance.now()` when that report landed. */
  private syncAt = 0;
  /** Monotonic measured playback position handed to the driver, ms. */
  private playedMs = 0;
  /** Whether the worklet has reported at all since the last reset. */
  private haveMetrics = false;
  /**
   * Speaker latency: audio already handed to the sound card but not yet audible.
   * The mouth must show what the EAR hears, so this is subtracted from the
   * worklet's position. On Windows/WASAPI it is routinely 100-200 ms, which on its
   * own is a plainly visible lead of the mouth over the voice.
   */
  private outputLatencyMs = 0;
  /** Viseme morphs written last frame, so they can be released. */
  private writtenVisemes = new Set<string>();
  /** True once a transcript arrived at all. */
  private textVisemesActive = false;
  /**
   * Whether text is driving the mouth *this frame*. Goes false when the queue
   * runs dry while audio is still playing, handing over to HeadAudio - without
   * that, a transcript that lags or drops leaves the mouth frozen.
   */
  private textInCharge = false;
  /** Set by notifyEnd(): the next `onAudioEnd` really is the end of the turn. */
  private turnEnded = false;
  /** Debug: pin one viseme so its shape can be inspected. `window.__hold`. */
  private heldViseme: string | null = null;
  /**
   * Debug: mouth text with NO audio at all. Runs the driver off a synthetic
   * clock, so it needs no AudioContext (hence no user gesture), no mic and no
   * Gemini session - just the loaded avatar. `window.__say`.
   */
  private dryRun = false;
  /** Debug: log the driving source and timing. `window.__lipsyncLog`. */
  private diagnose = false;
  private diagLastLog = 0;
  /** How long the shape queue has been dry while audio kept playing, ms. */
  private dryMs = 0;
  /**
   * Debug capture of the live timeline (`window.__lipsyncRecord`). Answers the
   * one question tuning cannot: does a transcript fragment arrive aligned in
   * CONTENT with the audio it describes, or does it trail it? If it trails, no
   * pacing scheme can be in sync and the audio has to be delayed instead.
   */
  private rec:
    | { at: number; kind: "tx" | "au"; fed: number; textMs: number; heard: number }[]
    | null = null;
  private recStart = 0;
  private recTextMs = 0;
  /** Where the lip-sync clock got reset, and how often. A clock that keeps
   *  returning to zero is why the capture showed audio_entregado=0 throughout. */
  private resetCounts: Record<string, number> = {};

  constructor(
    private node: HTMLElement,
    private callbacks: AvatarControllerCallbacks = {}
  ) {}

  get isReady(): boolean {
    return this._ready;
  }

  /** Create TalkingHead and load the avatar. Safe to call once. */
  async init(): Promise<void> {
    if (this.head || this.disposed) return;
    // Assign immediately so dispose() (e.g. StrictMode's double-mount) can tear
    // this instance down even while showAvatar is still loading.
    const head = new TalkingHead(this.node, {
      ttsEndpoint: "", // unused: TTS comes from Gemini Live
      // Empty so TalkingHead does NOT fire its dynamic import('./lipsync-en.mjs')
      // (404 in prod). We register the statically-imported processor right after
      // construction instead. Visemes come from HeadAudio/VisemeDriver anyway.
      lipsyncModules: [],
      lipsyncLang: "en",
      cameraView: "head",
      cameraRotateEnable: false,
      cameraPanEnable: false,
      cameraZoomEnable: false,
      // Warm, lively resting face from the first frame. "happy" carries a smile
      // baseline plus animated brows/head-sway/micro-mouth (see animMoods in
      // talkinghead.mjs) - all facial, so it costs nothing on the body rig and is
      // the expressiveness the arm gestures can't safely provide on this mesh.
      avatarMood: DEFAULT_MOOD,
      modelFPS: 30,
    });
    this.head = head;
    // Register the statically-bundled lip-sync processor (see import note). This
    // replaces TalkingHead's dynamic-import path so it works in the prod bundle.
    head.lipsync = { en: new LipsyncEn() };

    try {
      await head.showAvatar({
        url: AVATAR_URL,
        body: "F",
        lipsyncLang: "en",
        avatarMood: DEFAULT_MOOD,
      });
      if (this.disposed) return; // disposed mid-load → dispose() handles teardown
      // Framing tuned for the Manglara character (big afro): "head" view
      // crops her — "upper" + extra distance shows hair and shoulders.
      head.setView("upper", { cameraDistance: 1.5, cameraY: 0.5 });
      this.registerBodyLanguage(head);
      this.setupMouthSprite(head);
      // Single per-frame hook, wired before any streaming starts so the mouth
      // works regardless of whether HeadAudio (the fallback) ever loads.
      // TalkingHead calls this right before it applies morph targets.
      head.opt.update = (dt: number) => {
        this.updateVisemes(dt);
        // HeadAudio always ticks (it tracks the audio continuously), but its
        // morph writes are gated on `textInCharge` inside its onvalue hook -
        // both write the same `newvalue` slot, so only one may win per frame.
        // Running after us means it takes over cleanly when text runs dry.
        this.headAudio?.update(dt);
        this.drawMouth();
      };
      head.start();
      this._ready = true;
      // Expose for manual debugging in the console.
      const dbg = window as unknown as Record<string, unknown>;
      dbg.__head = head;
      dbg.__sayTest = (text: string) => this.testLipsync(text);
      // Audio-free lip-sync testing surface. See scripts/lipsync-console-test.js.
      dbg.__say = (text: string) => this.say(text);
      dbg.__phonemes = (text: string) => this.phonemesOf(text);
      dbg.__visemes = AvatarController.VISEMES;
      dbg.__mood = (mood: string) => {
        this.setMood(mood);
        console.log("[mood]", mood);
      };
      dbg.__body = (name: string) => {
        this.playBodyGesture(name);
        console.log("[body]", name);
      };
      dbg.__hold = (viseme: string | null) => {
        this.hold(viseme);
        console.log("[lipsync] holding", viseme ?? "(released)");
      };
      // Log what is actually driving the mouth, to settle sync questions with
      // data instead of guesswork.
      dbg.__lipsyncRecord = (on = true) => this.recordTimeline(on);
      dbg.__lipsyncReport = () => console.log(this.reportTimeline());
      dbg.__lipsyncLog = (on = true) => {
        this.diagnose = on;
        console.log("[lipsync] diagnostics", on ? "on" : "off");
      };
      this.callbacks.onReady?.();
    } catch (error) {
      this.callbacks.onError?.(error);
      throw error;
    }
  }

  // WebAudio Analyser for 100% real-time audio-driven lip-sync
  private analyserNode: AnalyserNode | null = null;
  private freqData: Uint8Array | null = null;
  private timeData: Uint8Array | null = null;

  /** Enter streaming mode and wire HeadAudio. Idempotent across calls. */
  async startStream(): Promise<void> {
    const head = this.head;
    console.log("[headaudio] startStream called; head?", !!head, "streaming?", this.streaming);
    if (!head || this.streaming) return;

    // Carry the tempo measured in earlier sessions in, so the very first turn of a
    // call is already calibrated instead of running on the duration table's guess.
    const seeded = loadPaceRate();
    if (seeded !== null) {
      this.driver.seedRate(seeded);
      console.log("[lipsync] tempo inicial aprendido:", seeded.toFixed(3));
    }

    await head.streamStart(
      {
        sampleRate: GEMINI_SAMPLE_RATE,
        lipsyncType: "visemes",
        // Switches on the playback worklet's queue reporting. The library defaults
        // it OFF, which is why the mouth had no real clock to run on.
        metrics: { enabled: true, intervalHz: PLAYBACK_METRICS_HZ },
      },
      () => this.callbacks.onSpeakingChange?.(true),
      () => {
        // Only clears on a real end of turn. `playback-ended` also fires on a
        // mid-sentence buffer underrun, and dropping pending shapes there is
        // exactly what makes the mouth stop partway through a phrase.
        if (this.turnEnded) {
          this.turnEnded = false;
          // End of turn is the ONLY moment the speaking tempo can be measured:
          // the transcript is complete, so audio/estimate is ground truth. The
          // driver keeps it across turns and uses it to lay out the next one.
          this.driver.endTurn(this.audioFedMs);
          savePaceRate(this.driver.rate);
          this.resetVisemeState("turn_complete");
        }
        this.callbacks.onSpeakingChange?.(false);
      },
      null, // onSubtitles: Gemini's transcript goes to feedTranscript instead
      (m) => this.onPlaybackMetrics(m)
    );
    this.streaming = true;
    this.resetVisemeState("startStream");

    // AFTER streamStart: it recreates the AudioContext when the requested sample
    // rate differs from the current one, so reading latency earlier would measure a
    // context that no longer exists.
    this.measureOutputLatency(head);

    // Wire WebAudio AnalyserNode directly to the playback audio bus for zero-latency lip sync
    if (head.audioStreamGainNode) {
      try {
        const analyser = head.audioCtx.createAnalyser();
        analyser.fftSize = 256;
        analyser.smoothingTimeConstant = 0.2;
        head.audioStreamGainNode.connect(analyser);
        this.analyserNode = analyser;
        this.freqData = new Uint8Array(analyser.frequencyBinCount);
        this.timeData = new Uint8Array(analyser.fftSize);
        console.log("[lipsync] AnalyserNode conectado a audioStreamGainNode");
      } catch (err) {
        console.warn("[lipsync] AnalyserNode setup error:", err);
      }
    }

    await this.setupHeadAudio(head);
  }

  /**
   * Read the speaker latency once per stream.
   *
   * `outputLatency` is the gap between audio leaving the graph and reaching the
   * ear. Where the browser doesn't report it, `baseLatency` (the graph's own
   * buffering) is the only signal available and is doubled as a rough stand-in for
   * the device buffer behind it.
   */
  private measureOutputLatency(head: TalkingHead): void {
    const ctx = head.audioCtx;
    const finite = (v: unknown): number =>
      typeof v === "number" && Number.isFinite(v) && v > 0 ? v : 0;
    const out = finite(ctx.outputLatency);
    const base = finite(ctx.baseLatency);
    const ms = (out > 0 ? out : base * 2) * 1000;
    this.outputLatencyMs = Math.min(Math.max(ms, 0), MAX_OUTPUT_LATENCY_MS);
    console.log(
      `[lipsync] latencia de salida ${Math.round(this.outputLatencyMs)}ms ` +
        `(outputLatency=${(out * 1000).toFixed(0)}ms baseLatency=${(base * 1000).toFixed(0)}ms) ` +
        `ctx.sampleRate=${ctx.sampleRate}`
    );
    if (ctx.sampleRate !== GEMINI_SAMPLE_RATE) {
      // The playback worklet copies PCM samples 1:1 into its output - it does NOT
      // resample. A mismatch here means the voice itself plays at the wrong speed
      // and pitch, which no lip-sync scheme can follow.
      console.error(
        `[lipsync] AudioContext corre a ${ctx.sampleRate}Hz pero el PCM es de ` +
          `${GEMINI_SAMPLE_RATE}Hz y el worklet no remuestrea: la voz sonará ` +
          `a ${(ctx.sampleRate / GEMINI_SAMPLE_RATE).toFixed(2)}x su velocidad.`
      );
    }
  }

  /**
   * The real playback position, from the worklet's queue depth.
   *
   * `queuedSamples` counts PCM handed over but not yet rendered, so
   * `audioFedMs - queued` is exactly how much audio has left the graph - a
   * measurement, not an estimate, and self-correcting on every report. Subtracting
   * the speaker latency turns it into what the ear is hearing right now.
   */
  private onPlaybackMetrics(msg: PlaybackMetricsMessage): void {
    const data = msg?.data;
    if (!data || typeof data.queuedSamples !== "number") return;
    if (data.state === 0) {
      if (this.audioFedMs > 0) {
        const heard = Math.max(0, this.audioFedMs - this.outputLatencyMs);
        this.syncPlayedMs = Math.min(heard, this.audioFedMs);
        this.syncAt = performance.now();
        this.haveMetrics = true;
      } else {
        this.haveMetrics = false;
      }
      return;
    }
    // Convert with OUR sample rate, not the worklet's `queuedMs`: the queue holds
    // the very samples `audioFedMs` counted, so this keeps both clocks on one
    // scale even if the AudioContext ended up at a different rate.
    const queuedMs = data.queuedSamples / (GEMINI_SAMPLE_RATE / 1000);
    const heard = this.audioFedMs - queuedMs - this.outputLatencyMs;
    this.syncPlayedMs = Math.min(Math.max(heard, 0), this.audioFedMs);
    this.syncAt = performance.now();
    this.haveMetrics = true;
  }

  /** Push a shape into the morph targets, releasing whatever was held before. */
  private writeVisemeMorphs(shape: string | null): void {
    const head = this.head;
    if (!head) return;
    const key = shape ? `viseme_${shape}` : null;

    const applyMorph = (k: string, val: number) => {
      const mt = head.mtAvatar[k];
      if (mt) {
        mt.newvalue = val;
        mt.needsUpdate = true;
        // Synchronously copy to Three.js morphTargetInfluences so drawMouth() reads current values immediately
        if (Array.isArray(mt.ms)) {
          for (let i = 0; i < mt.ms.length; i++) {
            if (mt.ms[i] && mt.is[i] !== undefined) {
              mt.ms[i][mt.is[i]] = val;
            }
          }
        }
      }
    };

    if (key) {
      const targetVal =
        shape === "PP" || shape === "FF" ? VISEME_LEVEL_CLOSED : VISEME_LEVEL;
      applyMorph(key, targetVal);
    }
    // Release anything held last frame.
    for (const prev of this.writtenVisemes) {
      if (prev === key) continue;
      applyMorph(prev, 0);
    }
    this.writtenVisemes.clear();
    if (key) this.writtenVisemes.add(key);
  }

  /**
   * The playback position for this frame, or undefined before the first report.
   *
   * Between reports the position is advanced by WALL time, never by the frame delta
   * - that delta is the clamped one described above. Each report re-anchors it, so
   * error cannot accumulate: the worst case is one report interval of extrapolation.
   */
  private measurePlayback(): number | undefined {
    if (!this.haveMetrics) return undefined;
    const ahead = Math.min(
      Math.max(performance.now() - this.syncAt, 0),
      METRICS_EXTRAPOLATE_MAX_MS
    );
    const next = Math.min(this.syncPlayedMs + ahead, this.audioFedMs);
    // Monotonic: a report crossing the thread boundary can describe a moment
    // already passed, and letting it pull the mouth backwards reads as a stutter.
    this.playedMs = Math.max(this.playedMs, next);
    return this.playedMs;
  }

  /** Feed one chunk of assistant PCM (24 kHz, 16-bit LE) for playback + lip-sync. */
  feedAudio(pcm: ArrayBuffer): void {
    if (!this.head || !this.streaming) return;
    this.turnEnded = false; // fresh audio: this turn is still going
    // MEASURE FIRST. `streamAudio` posts the ArrayBuffer to the worklet with a
    // transfer list (talkinghead.mjs: `postMessage(message, [message.data])`),
    // which DETACHES it - `pcm.byteLength` is 0 afterwards. Reading it after the
    // call meant `audioFedMs` never left 0, so `buffered` was always 0 and the
    // driver ran permanently at MAX_RATE (1.9x). That, not the pacing formula,
    // is why the live mouth was rushed and out of step.
    // 16-bit mono at 24 kHz → 48 bytes per ms.
    const chunkMs = pcm.byteLength / 2 / (GEMINI_SAMPLE_RATE / 1000);
    this.head.streamAudio({ audio: pcm });
    this.audioFedMs += chunkMs;
    this.record("au");
  }

  /**
   * Feed a fragment of the assistant's transcript to drive the mouth shapes.
   *
   * This is the primary lip-sync source: Gemini gives us the text of what
   * Manglara is saying, and Spanish spelling maps to phonemes reliably, so the
   * mouth can form the actual sounds instead of guessing them from the audio
   * waveform (see lipsync-es.ts).
   *
   * The fragments form a contiguous description of the turn's audio, and that -
   * not their arrival time - is what places them on the timeline. `audioFedMs` is
   * passed only as an upper bound; see viseme-driver.
   */
  feedTranscript(text: string): void {
    if (!this.head || !this.streaming) return;
    const units = spanishTextToUnits(text);
    if (!units.length) return;

    if (!this.textVisemesActive) {
      this.textVisemesActive = true;
      console.log("[lipsync] transcript-driven visemes active (HeadAudio muted)");
    }
    // The driver places this on the audio timeline itself, continuing where the
    // previous fragment's speech ended, and plays it when PLAYBACK reaches that
    // position. That is what puts mouth and voice together, instead of mouthing
    // text the moment it arrives (seconds early, since Gemini bursts far ahead of
    // playback).
    this.driver.enqueue(units, this.audioFedMs);
    this.recTextMs += unitsDuration(units);
    this.record("tx");
  }

  private record(kind: "tx" | "au"): void {
    if (!this.rec) return;
    this.rec.push({
      at: performance.now() - this.recStart,
      kind,
      fed: this.audioFedMs,
      textMs: this.recTextMs,
      heard: this.playedMs,
    });
  }

  /**
   * Start/stop capturing the live timeline. `window.__lipsyncRecord()` then
   * `window.__lipsyncReport()` after a few sentences.
   */
  recordTimeline(on = true): void {
    this.rec = on ? [] : null;
    this.recStart = performance.now();
    this.recTextMs = 0;
    console.log(`[lipsync] captura ${on ? "iniciada - habla unas frases" : "detenida"}`);
  }

  /**
   * The decisive number is `texto/audio`: how much speech the transcripts have
   * described versus how much audio has been delivered. Near 1 means they are
   * content-aligned and only pacing matters. Persistently below 1 means the
   * transcript trails its own audio, and then NO pacing scheme can be in sync -
   * the audio would have to be delayed to give the transcript a head start.
   */
  reportTimeline(): string {
    if (!this.rec || !this.rec.length) return "sin captura: llama a __lipsyncRecord() primero";
    const tx = this.rec.filter((r) => r.kind === "tx");
    const lines = tx.map((r) => {
      const ratio = r.fed > 0 ? r.textMs / r.fed : 0;
      // `adelanto` is the headroom the transcript has: how far the speech it
      // describes runs ahead of what the ear has already heard. Positive means the
      // text arrived in time to be mouthed; persistently negative means it is
      // describing audio that already played, and then nothing can be in sync.
      const lead = r.textMs * this.driver.rate - r.heard;
      return (
        `  t=${(r.at / 1000).toFixed(2)}s  oido=${Math.round(r.heard)}ms  ` +
        `audio_entregado=${Math.round(r.fed)}ms  texto_acumulado=${Math.round(r.textMs)}ms  ` +
        `texto/audio=${ratio.toFixed(2)}  adelanto=${Math.round(lead)}ms`
      );
    });
    const au = this.rec.filter((r) => r.kind === "au");
    const maxFed = Math.max(0, ...this.rec.map((r) => r.fed));
    const resets = Object.entries(this.resetCounts)
      .map(([k, n]) => `${k}=${n}`)
      .join(" ");
    const last = tx[tx.length - 1]!;
    // Compare TOTALS at the end of the capture, not the values at the last
    // transcript event: a fragment legitimately arrives before its own audio, so
    // reading `fed` at that instant understates it.
    const overall = maxFed > 0 ? last.textMs / maxFed : 0;
    const burst = last.at > 0 ? maxFed / last.at : 0;

    // A clock that never leaves zero is not a lag measurement, it is a bug: the
    // ratio is only meaningful once audio_entregado actually accumulates.
    const verdict =
      maxFed === 0
        ? "audioFedMs NUNCA subió de 0 → feedAudio() no corre o el reloj se resetea. " +
          "Mira los resets y los chunks de audio de abajo, NO es una medida de desfase."
        : overall > 0.85
          ? "alineados: el problema es de ritmo"
          : "el transcript va POR DETRÁS de su audio: habría que retrasar el audio";

    const clock = this.haveMetrics
      ? `MEDIDO desde el worklet (latencia de salida ${Math.round(this.outputLatencyMs)}ms)`
      : "SIN DATOS del worklet - metrics no llegaron, revisa streamStart";

    return [
      `fragmentos de transcript: ${tx.length}   chunks de audio: ${au.length}`,
      `reloj de reproduccion: ${clock}`,
      `audioFedMs máximo visto: ${Math.round(maxFed)}ms   oido: ${Math.round(this.playedMs)}ms`,
      `tempo aprendido: ${this.driver.rate.toFixed(3)} (audio ms por ms estimado)`,
      `resets del reloj: ${resets || "ninguno"}`,
      `ráfaga de audio: ${burst.toFixed(1)}x tiempo real`,
      `RATIO GLOBAL texto/audio: ${overall.toFixed(2)}  (${verdict})`,
      "--- ultimos chunks de audio ---",
      ...au
        .slice(-8)
        .map(
          (r) =>
            `  t=${(r.at / 1000).toFixed(2)}s  fed=${Math.round(r.fed)}ms  oido=${Math.round(r.heard)}ms`
        ),
      "--- ultimos fragmentos de transcript ---",
      ...lines.slice(-12),
    ].join("\n");
  }

  /**
   * Advance the mouth one frame. Called from `opt.update`, which TalkingHead
   * runs immediately before it applies morph targets.
   */
  private updateVisemes(dt: number): void {
    const head = this.head;
    if (!head) return;

    // Debug pin (window.__hold) overrides everything so a single shape can be
    // inspected on screen for as long as needed.
    if (this.heldViseme !== null) {
      this.textInCharge = true;
      this.writeVisemeMorphs(this.heldViseme);
      return;
    }

    // Audio-free preview (window.__say), pinned to natural pace.
    if (this.dryRun) {
      const backlog = this.driver.backlogMs;
      if (backlog <= 0) {
        this.dryRun = false;
        this.textInCharge = false;
        this.writeVisemeMorphs(null);
        return;
      }
      this.textInCharge = true;
      this.writeVisemeMorphs(
        this.driver.tick({
          dt,
          speaking: true,
          // No real audio: let the playback clock run free at natural pace.
          audioFedMs: Number.MAX_SAFE_INTEGER,
          naturalPace: true,
        })
      );
      return;
    }

    // `isSpeaking` only gates whether the mouth may move at all. It is set the
    // instant a chunk is POSTED to the worklet, well before a sample is rendered,
    // so it must never be the timing source - the measured clock below stays at 0
    // until audio is genuinely consumed, which is what stops the mouth starting
    // ahead of the voice.
    const speaking = head.isSpeaking === true;
    let shape: string | null = null;

    if (speaking && this.analyserNode && this.freqData && this.timeData) {
      this.analyserNode.getByteFrequencyData(this.freqData);
      this.analyserNode.getByteTimeDomainData(this.timeData);
      shape = this.driver.tickFrame({
        dt,
        frequencyData: this.freqData,
        timeDomainData: this.timeData,
      });
    } else {
      shape = this.driver.tick({
        dt,
        speaking,
        audioFedMs: this.audioFedMs,
        playedMs: this.measurePlayback(),
      });
    }

    this.textInCharge = true;
    this.writeVisemeMorphs(shape);

    if (this.diagnose) {
      this.diagLastLog += dt;
      if (this.diagLastLog >= 250) {
        this.diagLastLog = 0;
        console.log(
          `[lipsync] ${speaking ? "AUDIO" : "silencio"} ` +
            `fuente=audio-analyser ` +
            `forma=${shape ?? "-"} ` +
            `oido=${Math.round(this.playedMs)}ms ` +
            `entregado=${Math.round(this.audioFedMs)}ms`
        );
      }
    }
  }

  /** Drop all pending mouth shapes and reset the lip-sync clock. */
  private resetVisemeState(why: string): void {
    this.resetCounts[why] = (this.resetCounts[why] ?? 0) + 1;
    this.driver.reset();
    this.audioFedMs = 0;
    this.textInCharge = false;
    this.dryMs = 0;
    // The playback clock is relative to `audioFedMs`, so it has to go with it.
    this.syncPlayedMs = 0;
    this.syncAt = 0;
    this.playedMs = 0;
    this.haveMetrics = false;
  }

  /** Signal the current utterance is complete (playback drains then idles). */
  notifyEnd(): void {
    if (!this.streaming) return;
    // Distinguishes a real end of turn from a mid-sentence buffer underrun:
    // both surface as `onAudioEnd`, but only here may leftover shapes be
    // dropped. Carrying them into the next turn would desync it from the start.
    this.turnEnded = true;
    this.head?.streamNotifyEnd();
  }

  /**
   * Debug helper (exposed as `window.__sayTest`): mouth the given text with
   * SILENT audio, so lip readability can be judged without a Gemini call.
   * Silence keeps TalkingHead's stream clock running, which is what the viseme
   * schedule is anchored to.
   */
  async testLipsync(text: string): Promise<void> {
    if (!this.head) return;
    if (!this.streaming) await this.startStream();
    const units = spanishTextToUnits(text);
    const total = unitsDuration(units);
    console.log(
      "[lipsync] test:",
      units.map((u) => u.viseme ?? "_").join(" "),
      `${Math.round(total)}ms`
    );
    // Transcript first, then its audio - the order Gemini sends them in.
    this.feedTranscript(text);
    const samples = Math.ceil(((total + 400) * GEMINI_SAMPLE_RATE) / 1000);
    this.feedAudio(new ArrayBuffer(samples * 2));
    this.notifyEnd();
  }

  /**
   * Mouth a phrase with NO audio (window.__say). Needs only the loaded avatar:
   * no AudioContext, no mic, no Gemini session. Resolves when the mouth is done,
   * so a caller can chain phrases.
   */
  say(text: string): Promise<void> {
    const units = spanishTextToUnits(text);
    if (!units.length || !this.head) return Promise.resolve();
    this.heldViseme = null;
    this.driver.reset();
    this.textVisemesActive = true;
    this.driver.enqueue(units);
    this.dryRun = true;
    const totalMs = unitsDuration(units);
    return new Promise((resolve) => {
      const started = performance.now();
      const check = (): void => {
        // Wait for the queue to drain, with a ceiling in case rendering stalls
        // (the avatar's animation loop only runs while the tab is visible).
        if (!this.dryRun || performance.now() - started > totalMs + 2000) {
          resolve();
          return;
        }
        requestAnimationFrame(check);
      };
      requestAnimationFrame(check);
    });
  }

  /** Viseme ids available to `hold()`, in articulation order. */
  static readonly VISEMES = [
    "sil", "PP", "FF", "TH", "DD", "nn", "kk", "CH", "SS", "RR",
    "aa", "E", "I", "O", "U",
  ];

  /** Pin one viseme on screen, or null to release. */
  hold(viseme: string | null): void {
    this.dryRun = false;
    this.heldViseme = viseme;
  }

  /** The viseme sequence a phrase produces, for comparing against the mouth. */
  phonemesOf(text: string): string {
    return spanishTextToUnits(text)
      .map((u) => u.viseme ?? "·")
      .join(" ");
  }

  /**
   * Barge-in: drop everything queued for this turn.
   *
   * Gemini streams audio far ahead of playback, so on an interruption there is a
   * lot of already-delivered audio AND a matching pile of pending mouth shapes
   * that are now both cancelled. Without this the buffered audio keeps playing
   * while the mouth works through its stale queue, and since neither clock is
   * reset the desync persists for the rest of the session and compounds with
   * every further interruption.
   */
  interrupt(): void {
    if (!this.streaming) return;
    console.warn("[lipsync] interrupt(): descartando el turno en curso");
    this.turnEnded = false;
    this.head?.streamInterrupt(); // stops playback and purges queued visemes
    this.resetVisemeState("interrupted");
    this.writeVisemeMorphs(null); // release the shape being held
  }

  /** Leave streaming mode (keeps the avatar mounted and idle). */
  stopStream(): void {
    if (!this.streaming) return;
    this.head?.streamStop();
    this.streaming = false;
    this.resetVisemeState("stopStream");
    this.textVisemesActive = false;
  }

  /** Map the call state machine to gaze + facial mood. */
  setState(state: AvatarState): void {
    const head = this.head;
    if (!head || !this._ready || state === this.lastState) return;
    this.lastState = state;
    if (state === "thinking") {
      // Pondering: glance away and let the face settle to a calmer, neutral read
      // so the "thinking" beat is legible against the warm speaking face.
      this.setMood(THINKING_MOOD);
      head.lookAhead(2000);
      this.stopBodyLanguage();
    } else if (state === "speaking") {
      // Warm and animated while presenting: eye contact plus the "happy" mood's
      // speaking animation (brows, head-sway, micro-mouth) PLUS rig-safe torso/
      // head body language (lean-in, nods, tilts) - lively presenting without
      // touching the arm rig that would balloon the dress.
      this.setMood(DEFAULT_MOOD);
      head.makeEyeContact(3000);
      this.startBodyLanguage();
    } else {
      // idle / listening: attentive, smiling, looking at the user, with a single
      // gentle lean-in so she reads as actively listening.
      this.setMood(DEFAULT_MOOD);
      head.lookAtCamera(500);
      this.stopBodyLanguage();
      this.playBodyGesture("leanIn");
    }
  }

  /**
   * Register the rig-safe body-language poses (see BODY_GESTURES) into
   * TalkingHead's gestureTemplates so `playGesture` can drive them. Touches only
   * torso/neck/head bones, so it never balloons the arm-welded dress.
   */
  private registerBodyLanguage(head: TalkingHead): void {
    if (!head.gestureTemplates) return;
    for (const [name, tmpl] of Object.entries(BODY_GESTURES)) {
      head.gestureTemplates[name] = tmpl as Record<string, unknown>;
    }
  }

  /** Play one body-language beat; holds briefly then eases back to idle. */
  private playBodyGesture(name: string): void {
    const head = this.head;
    if (!head) return;
    try {
      head.playGesture(name, 2.5, this.bodyLangMirror, 700);
    } catch {
      // Unknown template / build mismatch: skip rather than break the call.
    }
    this.bodyLangMirror = !this.bodyLangMirror;
  }

  /** Start the speaking-time body-language loop (idempotent). */
  private startBodyLanguage(): void {
    if (this.bodyLangTimer || !this.head) return;
    const tick = () => {
      const name =
        BODY_GESTURE_POOL[Math.floor(Math.random() * BODY_GESTURE_POOL.length)];
      this.playBodyGesture(name);
      this.bodyLangTimer = setTimeout(tick, 3500 + Math.random() * 2500);
    };
    // First beat shortly after she starts speaking.
    this.bodyLangTimer = setTimeout(tick, 600);
  }

  /** Stop the loop and relax any held pose back to idle. */
  private stopBodyLanguage(): void {
    if (this.bodyLangTimer) {
      clearTimeout(this.bodyLangTimer);
      this.bodyLangTimer = null;
    }
    try {
      this.head?.stopGesture(600);
    } catch {
      // ignore
    }
  }

  /** Set the facial mood (face + head-sway only; never touches the body rig). */
  setMood(mood: string): void {
    const head = this.head;
    if (!head) return;
    try {
      head.setMood(mood);
    } catch {
      // Unknown mood name (build mismatch): keep the current face rather than throw.
    }
  }

  dispose(): void {
    this.disposed = true;
    this.stopBodyLanguage();
    this.stopStream();
    try {
      this.headAudio?.disconnect?.();
      if (this.head) {
        this.head.opt.update = undefined;
        this.head.stop();
        this.head.dispose();
      }
    } catch {
      // ignore teardown errors
    }
    // Remove any leftover canvas so a fresh controller starts clean.
    try {
      while (this.node.firstChild) this.node.removeChild(this.node.firstChild);
    } catch {
      // ignore
    }
    this.mouthTex?.dispose();
    this.mouthMesh = null;
    this.mouthCtx = null;
    this.mouthTex = null;
    this.lastShape = null;
    this.headAudio = null;
    this.headAudioReady = false;
    this.head = null;
    this._ready = false;
  }

  /** Find the MouthOverlay patch exported by the rig pipeline and give it a
   *  CanvasTexture we can repaint per frame. Non-fatal if missing (older GLB). */
  private setupMouthSprite(head: TalkingHead): void {
    try {
      const root = (head as unknown as { armature?: Mesh }).armature;
      let overlay: Mesh | null = null;
      root?.traverse?.((o) => {
        if ((o as Mesh).isMesh && o.name === "MouthOverlay") overlay = o as Mesh;
      });
      if (!overlay) {
        console.warn("[mouth] MouthOverlay mesh not found in avatar GLB");
        return;
      }
      const canvas = document.createElement("canvas");
      canvas.width = 512;
      canvas.height = 256;
      const ctx = canvas.getContext("2d");
      if (!ctx) return;
      const tex = new CanvasTexture(canvas);
      tex.colorSpace = SRGBColorSpace;
      tex.flipY = false; // glTF UV convention (v=0 at the top of the patch)
      (overlay as Mesh).material = new MeshBasicMaterial({
        map: tex,
        transparent: true,
        depthWrite: false,
      });
      (overlay as Mesh).renderOrder = 2;
      this.mouthMesh = overlay;
      this.mouthCtx = ctx;
      this.mouthTex = tex;
      // Expose for manual debugging in the console.
      (window as unknown as Record<string, unknown>).__drawMouth = () => this.drawMouth();
      console.log("[mouth] sprite overlay ready");
    } catch (error) {
      console.warn("[mouth] sprite setup failed:", error);
    }
  }

  /** Repaint the mouth sprite from the overlay's CURRENT morph influences
   *  (already eased by TalkingHead, so the sprite is perfectly in sync with
   *  the jaw/chin deformation). Called every render frame via opt.update. */
  private drawMouth(): void {
    const mesh = this.mouthMesh;
    const ctx = this.mouthCtx;
    const tex = this.mouthTex;
    if (!mesh || !ctx || !tex) return;
    const dict = mesh.morphTargetDictionary;
    const inf = mesh.morphTargetInfluences;
    if (!dict || !inf) return;
    const v = (k: string): number => {
      const i = dict[k];
      return i === undefined ? 0 : inf[i] ?? 0;
    };

    // Use the organically LERP-interpolated lip shape computed by AudioVisemeEngine
    const shape = this.driver.currentLipShape ?? blendLipShapes((viseme) => v(`viseme_${viseme}`));

    // Skip the repaint when nothing moved perceptibly.
    if (
      this.lastShape &&
      Math.abs(shape.aperture - this.lastShape.aperture) < 0.006 &&
      Math.abs(shape.width - this.lastShape.width) < 0.01 &&
      Math.abs(shape.round - this.lastShape.round) < 0.02 &&
      Math.abs(shape.protrude - this.lastShape.protrude) < 0.02 &&
      Math.abs(shape.upperTeeth - this.lastShape.upperTeeth) < 0.03 &&
      Math.abs(shape.tongue - this.lastShape.tongue) < 0.04 &&
      Math.abs(shape.lipOnTeeth - this.lastShape.lipOnTeeth) < 0.02
    ) {
      return;
    }
    this.lastShape = shape;

    // Canvas space: the pipeline maps the painted lip line to a constant
    // v = 0.375 from the top of the patch, so a straight sprite follows the
    // smile curve on the mesh automatically.
    const W = 512;
    const H = 256;
    const cx = W / 2;
    const lineY = 0.375 * H;
    ctx.clearRect(0, 0, W, H);
    ctx.lineJoin = "round";

    const { aperture, width, round, protrude, tongue, lipOnTeeth } = shape;

    // /f/ and /v/: the lips barely part, so the identifying cue has to be drawn
    // even though aperture is tiny - upper teeth biting the lower lip.
    if (aperture <= 0.03 && lipOnTeeth <= 0.03) {
      tex.needsUpdate = true; // sealed: the painted lips already read correctly
      return;
    }

    // Aperture outline. Corners sit on the painted lip line; `round` pulls them
    // inward and `protrude` shrinks the hole to a pucker.
    const hw = W * (0.18 + 0.22 * width) * (1 - 0.22 * protrude);
    const up = aperture * (0.09 + 0.13 * round) * H;
    const down = aperture * (0.34 + 0.12 * round) * H;
    const corner = 1 - 0.55 * round; // how far the curve reaches the corners
    const openH = up + down; // height of the aperture; drives the interior layout

    const path = new Path2D();
    path.moveTo(cx - hw, lineY);
    path.bezierCurveTo(cx - hw * corner, lineY - up, cx + hw * corner, lineY - up, cx + hw, lineY);
    path.bezierCurveTo(cx + hw * corner, lineY + down, cx - hw * corner, lineY + down, cx - hw, lineY);

    // Lip outline FIRST, so the fills below cover its inner half and only the
    // outer half shows. Stroking last instead ate 3px inward all the way round -
    // on a thin aperture like /s/ (17px tall) that is a third of the opening
    // turned black, burying the teeth and tongue and reading as an empty hole.
    ctx.strokeStyle = "rgba(72, 27, 16, 0.92)";
    ctx.lineWidth = 6 + 9 * protrude;
    ctx.stroke(path);

    const cavity = ctx.createLinearGradient(0, lineY - up, 0, lineY + down);
    cavity.addColorStop(0, "#42150f");
    cavity.addColorStop(1, "#1e0806");
    ctx.fillStyle = cavity;
    ctx.fill(path);

    ctx.save();
    ctx.clip(path);

    // The tongue is ALWAYS there in an open mouth - what varies is how high it
    // rises (tip at the alveolar ridge for /t/, /d/, /n/, /l/; low and flat for
    // /a/). Gating it on a low `tongue` value left wide vowels as an empty black
    // hole, and centring the ellipse below the cavity floor meant the clip threw
    // nearly all of it away. Draw it as a mass rising from the floor instead.
    const tongueTop = lineY + down - openH * (0.36 + 0.42 * tongue);
    const tg = ctx.createLinearGradient(0, tongueTop, 0, lineY + down);
    tg.addColorStop(0, "#c2685a");
    tg.addColorStop(1, "#8e3b33"); // shaded where it meets the floor
    ctx.fillStyle = tg;
    ctx.beginPath();
    const tongueH = lineY + down - tongueTop + 10;
    // Radii MUST be clamped to the box: a radius larger than half the height
    // collapses the shape. hw*0.5 is ~80px, so on a thin aperture the tongue and
    // the teeth bands were being rounded away almost entirely.
    const tongueR = Math.min(hw * 0.5, tongueH * 0.45);
    ctx.roundRect(cx - hw * 0.92, tongueTop, hw * 1.84, tongueH, [tongueR, tongueR, 6, 6]);
    ctx.fill();
    // Centre crease, the detail that stops it reading as a flat pink slab.
    ctx.strokeStyle = "rgba(110,40,34,0.45)";
    ctx.lineWidth = 3;
    ctx.beginPath();
    ctx.moveTo(cx, tongueTop + openH * 0.06);
    ctx.lineTo(cx, lineY + down);
    ctx.stroke();

    // Teeth rows. Visibility differs per viseme and is a strong readability cue:
    // /s/ shows both rows nearly meeting, /o/ and /u/ hide them almost entirely.
    const enamel = "#f6f1e6";

    // Order matters: lower teeth, then the /f/ lip tuck, then the upper teeth
    // LAST. For /f/ and /v/ the teeth have to sit visibly ON the lower lip;
    // painting the lip afterwards buried them and made /f/ read as a shut mouth.
    if (shape.lowerTeeth > 0.05) {
      const th = openH * 0.2 * shape.lowerTeeth;
      const top = lineY + down - th;
      const tw = hw * 1.56;
      const grad = ctx.createLinearGradient(0, top, 0, top + th + 8);
      grad.addColorStop(0, "#fffdf7");
      grad.addColorStop(1, "#cdc2b1"); // shadowed towards the gum
      ctx.fillStyle = grad;
      ctx.beginPath();
      const r = Math.min(9, (th + 8) * 0.4); // clamped: see the tongue note below
      ctx.roundRect(cx - tw / 2, top, tw, th + 8, [r, r, 4, 4]);
      ctx.fill();
    }
    if (lipOnTeeth > 0.05) {
      ctx.globalAlpha = lipOnTeeth;
      ctx.fillStyle = "#8d3a2c";
      ctx.beginPath();
      ctx.roundRect(cx - hw, lineY + down - openH * 0.45, hw * 2, down + 12, 12);
      ctx.fill();
      ctx.globalAlpha = 1;
    }
    if (shape.upperTeeth > 0.05) {
      // Composition of an open mouth, as fractions of the aperture: a teeth band
      // at the top, dark in the middle, tongue filling the bottom. Scaling this
      // by the canvas height made a wide /a/ 73% teeth; shrinking it to a fixed
      // 22 px swung the other way and left the mouth looking empty.
      const th = openH * (0.14 + 0.32 * shape.upperTeeth);
      const top = lineY - up - 6;
      const h = th + 6;
      const tw = hw * 1.72;
      // A flat white rectangle reads as a blotch, not as teeth. A gum-line
      // shadow, a brighter biting edge and faint incisor gaps make it read.
      const grad = ctx.createLinearGradient(0, top, 0, top + h);
      grad.addColorStop(0, "#cbbfae");
      grad.addColorStop(0.4, enamel);
      grad.addColorStop(1, "#fffdf7");
      ctx.fillStyle = grad;
      ctx.beginPath();
      const r = Math.min(11, h * 0.4); // clamped: see the tongue note above
      ctx.roundRect(cx - tw / 2, top, tw, h, [4, 4, r, r]);
      ctx.fill();
      ctx.strokeStyle = "rgba(146,128,108,0.32)";
      ctx.lineWidth = 2;
      for (const f of [-0.28, -0.1, 0.1, 0.28]) {
        ctx.beginPath();
        ctx.moveTo(cx + tw * f, top + h * 0.4);
        ctx.lineTo(cx + tw * f, top + h);
        ctx.stroke();
      }
    }

    ctx.restore();

    tex.needsUpdate = true;
  }

  /** One-time HeadAudio setup: worklet + model + tap the streaming audio bus. */
  private async setupHeadAudio(head: TalkingHead): Promise<void> {
    if (this.headAudioReady) return;
    try {
      const log = (...a: unknown[]) => console.log("[headaudio]", ...a);
      log("setup start; ctx.sampleRate =", head.audioCtx.sampleRate);

      await head.audioCtx.audioWorklet.addModule(`${HEADAUDIO_BASE}/headworklet.min.mjs`);
      log("worklet added");

      const mod = await import(/* @vite-ignore */ `${HEADAUDIO_BASE}/headaudio.min.mjs`);
      const HeadAudio = mod.HeadAudio;
      log("module imported; HeadAudio =", typeof HeadAudio);

      // visemeEventsEnabled/vadEventsEnabled surface the onviseme/onvad
      // callbacks used below for diagnostics.
      const ha = new HeadAudio(head.audioCtx, {
        processorOptions: {
          sampleRate: head.audioCtx.sampleRate,
          visemeEventsEnabled: true,
          vadEventsEnabled: true,
        },
      });
      await ha.loadModel(`${HEADAUDIO_BASE}/model-en-mixed.bin`);
      log("model loaded");

      // Tap the streaming playback bus (streaming audio routes through
      // audioStreamGainNode, not audioSpeechGainNode).
      head.audioStreamGainNode.connect(ha);

      // Fallback only. Transcript-driven visemes are far more legible, so
      // HeadAudio yields the mouth whenever text has something to say. It stays
      // wired for the cases text can't cover: transcription disabled, lagging
      // badly, or dropping mid-turn - otherwise the mouth would just freeze.
      let valueCount = 0;
      ha.onvalue = (key: string, value: number) => {
        if (this.textInCharge) return;
        const mt = head.mtAvatar[key];
        if (mt) {
          mt.newvalue = value;
          mt.needsUpdate = true;
        }
        if (valueCount < 12 && value > 0.01) {
          valueCount++;
          log("onvalue", key, value.toFixed(3), mt ? "(mapped)" : "(NO morph!)");
        }
      };
      // Diagnostics: does the worklet detect speech / visemes from the audio?
      let visemeCount = 0;
      ha.onviseme = (o: { viseme?: string }) => {
        if (visemeCount < 12) {
          visemeCount++;
          log("onviseme", o?.viseme);
        }
      };
      // Bounded: this fires continuously while audio flows, and an unbounded
      // console.log on that path stalls the main thread enough to hitch the render
      // loop - which freezes the mouth mid-word. Verified flooding the console.
      let vadCount = 0;
      ha.onvad = (o: unknown) => {
        if (vadCount < 8) {
          vadCount++;
          log("onvad", o);
        }
      };

      // NOTE: opt.update is wired in init(), not here - the mouth must keep
      // working even if this whole HeadAudio setup fails.

      // Expose for manual debugging in the console.
      (window as unknown as Record<string, unknown>).__head = head;
      (window as unknown as Record<string, unknown>).__headaudio = ha;

      this.headAudio = ha;
      this.headAudioReady = true;
      log("setup OK; opt.update wired");
    } catch (error) {
      // Non-fatal: audio still plays via TalkingHead, only lip-sync is lost.
      console.error("[headaudio] setup FAILED:", error);
      this.callbacks.onError?.(error);
    }
  }
}
